version: "3"

services:
  spring-app:
    container_name: app-backend
    image: app-backend
    ports:
      - "8080:8080"
    networks:
      - spring-mysql
    depends_on:
      - leiladb

  leiladb:
    container_name: app-mysqldb
    image: mysql
    ports:
      - "3306:3306"
    networks:
      - spring-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=ems

networks:
  spring-mysql:
    driver: bridge